### ISSUE TITLE
IE9 'router.ref' error in React.render

### ISSUE THREAD

**Issue by spicydonuts** [STRML/react-router-component#110]
Getting an error in IE9 only when React initially loads: "Unable to get property 'ref' of undefined or null reference"

Here's the line that throws:
```javascript
/**
 * Mixin for routers which implements the simplest rendering strategy.
 */
var RouteRenderingMixin = {

  renderRouteHandler: function(props) {
    var handler = this.state.handler;
    props = assign({ref: this.state.match.route.ref}, props); // <----[ Error on this line ]
    // If we were passed an element, we need to clone it before passing it along.
    if (React.isValidElement(handler)) {
      return cloneWithProps(handler, props);
    }
    return React.createElement(handler, props);
  }

};
```

Here are the two Locations I'm using:
```javascript
<Locations ref="router">
	<Location path="/app" handler={App} />
	<Location path="/app/:id" handler={App} />
</Locations>
```

App is pretty simple right now -- both routes use the same handler, which renders a modal when an `id` prop exists.  Mostly just using the router for the history api features.

Tried stepping through the code a bit but I'm not sure where that property is supposed to come from.  No other scripts or shims on the page.

**Comment by STRML** [comment]
Okay - the `ref` property is sometimes undefined, but `match.route` should always be defined.

`match` is the Match object defined [here](https://github.com/STRML/react-router-component/blob/master/lib/matchRoutes.js#L83). It has a `route` property that refers to the `<Location>` that matched.

I see that it is actually possible that this reference would be undefined if the current route doesn't match any `<Location>`s and you have no `<NotFound>` route. Can you try adding one and see if it fixes your issue? If it does, I will make a quick patch to make sure this doesn't throw an error.

**Comment by spicydonuts** [comment]
Good timing, I just discovered the unmatched route problem a few minutes ago!  Looks like the default environment in IE9 is hash, while everything else uses history.  I'd like to keep everything on history and have IE9 fall back on regular <a href> behavior, since users may share urls and they need to be consistent.  Is there already a way to do this?  I'll try setting <Locations hash={false}> real quick.

**Comment by spicydonuts** [comment]
Actually, looking at `getEnvironment()`, `hash={false}` is the same as not providing one.  I'll try passing in the `Environment.pathnameEnvironment` env explicitly.

**Comment by spicydonuts** [comment]
`<Locations environment={new Router.environment.PathnameEnvironment()}>` worked for supported browsers, but there is no logic for "just allow event default if pushState is not supported".  Do you think that logic would make sense in `PathnameEnvironment` or should there be a different fallback for IE9 like a new `ReloadingPathnameEnvironment`?

In general, it seems weird that the defaults (not providing `hash` or setting `hash={false}`) would result in completely different routers on different browsers, since route paths are not shareable between the pathname and hash environments.  Maybe instead of messing with `PathnameEnvironment` it would be better to have `HashEnvironment` use the path if there was no hash set, meaning `"/somepath"` and `"/somepath#/` wouldn't be the same thing.  That way if you want single page behavior you could leave the `hash` prop off completely, but if you want to disable hashing entirely you could set `hash={false}`, in which case any code that would have changed or set the browser's hash path could instead set `window.location.href`.

The latter feels cleaner since `hash={false}` doesn't mean anything right now, and the `defaultEnvironment` logic already exists.

**Comment by STRML** [comment]
Michael - this is something I'll look into. @andreypopp wrote the
environment logic and since then my maintenance work hasn't involved
touching that code.

Once I find some time soon I will look through this and see what can be
done to make the environments interoperate well. Please feel free to add
any other comments that you think I may find useful in deciding how to
handle this.

**Comment by spicydonuts** [comment]
The change above seems fairly safe, since routing behaves so differently between hash and pathname environments right now.  As a result I imagine current users either have `hash={true}` (behavior that wouldn't change) or are completely ignoring without `pushState` support.

Since I need this to work I'll work on a PR to prototype these changes.

BTW, I hate the approach most React routers are taking of making routes a separate structure that owns the entire React.render call.  `react-router` was rebuilding my entire app on any route change, even to the same page, which is ridiculous.  I'd like to work on a slightly more data-driven approach at some point, but your api is pretty close.  Thanks a bunch!

**Comment by STRML** [comment]
Sounds great, a PR would be very helpful. Thanks in advance for that.
