### ISSUE TITLE
External/full links should bypass react-router-component

### ISSUE THREAD

**Issue by ftorre104** [STRML/react-router-component#111]
In order to integrate with legacy sites, we need react router to hijack the links or send the user to a hardcoded url.
It'd be nice for react-router-component to simply pass through requests for full links.

ie

    React.createElement(Link, {
        href: 'http://example.com/page1',
    }, 'Click here')

Currently, if you try to do an external link through react-router-component, as shown above you'll end up navigating to something like `http://mydomain:3000/example.com/page1` which will in most cases hit the react-router-component NotFound page.

Because 'http://example.com/page1' is a full link, it should escape the react-router component and do a normal browser request.

**Comment by STRML** [comment]
You can do this by setting `rel="external"` on the links you click.

**Comment by ftorre104** [comment]
Doesn't seem to work...

    React.createElement(Link, {
        className: 'sitemap-link',
        href: paths.ProfilePage,
        rel: 'external'
    }, 'See your profile')

That did add the rel="external" attribute to the <a> element in the DOM, but didn't change any behavior.

The link needs to be built using the <Link> component. Depending on a config variable, legacyIntegration, the paths will need to be relative to the current project or full URLS (to integrate with a legacy site). In the case shown above, paths.ProfilePage will either be '/profile' or 'http://legacysite.com/profile'

**Comment by ftorre104** [comment]
Apparently

    React.createElement(Link, {
        className: 'sitemap-link',
        href: 'http://example.com/profile',
        rel: 'external'
    }, 'See your profile')

Is being translated into:
    
    <a class="sitemap-link" href="http:/example.com/profile" rel="external" data-reactid=".2f156eg3aio.1.0.0.0.1.4">See your profile</a>

However, I tried updating the html on the fly to a syntactically correct full link `http://example.com`.
https://www.dropbox.com/s/z712upmm4eihuxh/Screenshot%202015-01-12%2010.55.46.png?dl=0
But react-router-component still grabs it on click and makes it relative: `http://localhost:3000/example.com/profile`

**Comment by STRML** [comment]
I see. The issue is that |rel="external"| is only a switch on
|<CaptureClicks>|. A |<Link>| component, if created, will always cause
an in-app navigation unless the event is cancelled via an onClick handler.

You have a few options:

  * Conditionally create an |<a>| or |<Link>| depending on
    |legacyIntegration|
  * Surround |<Locations>| in |<CaptureClicks>| (see
    http://strml.viewdocs.io/react-router-component/a-elements) and add
    |rel="external"| depending on |legacyIntegration|
  * Create a wrapper component around |<Link>| that conditionally
    renders a bare |<a>| if |legacyIntegration|, or alternatively always
    creates a |<Link>| with an onClick handler that calls
    |e.preventDefault()| depending on your legacy switch.

I would be happy to accept a PR that automatically cancels navigation on
a |<Link>| if the link goes to another domain. It should be easy to
figure that out by parsing the url to figure out if it is relative or
absolute. We already include the |urllite| module so it can be used for
this purpose without adding significant weight to the library.

On 1/12/15 7:47 PM, Fede Torre Mtz wrote:

> Doesn't seem to work...
>
> |React.createElement(Link, {
>     className: 'sitemap-link',
>     href: paths.ProfilePage,
>     rel: 'external'
> }, 'See your profile')
> |
>
> That did add the rel="external" attribute to the element in the DOM,
> but didn't change any behavior.
>
> The link needs to be built using the component. Depending on a config
> variable, legacyIntegration, the paths will need to be relative to the
> current project or full URLS (to integrate with a legacy site). In the
> case shown above, paths.ProfilePage will either be '/profile' or
> 'http://legacysite.com/profile'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STRML/react-router-component/issues/111#issuecomment-69622079>.
>
​

**Comment by ftorre104** [comment]
Yeah, that's what I figured -- I could just create <a> if legacy as opposed to <Link>.

I'll work on building it and getting a PR in with 2 objectives:
1) fix makeHref() for full URL links
2) bypass the router on full URL links

(thanks for the quick responses btw!!)

**Comment by ftorre104** [comment]
I have made the changes on a local branch, but don't have permission to push it. Would you need to add me?

**Comment by STRML** [comment]
You need to open a pull request.

**Comment by spicydonuts** [comment]
Is this working as you described on your branch?  Do you think you'll submit a pull request soon?

**Comment by STRML** [comment]
Published as `0.24.0`.
