### ISSUE TITLE
Render NotFound after successful navigation?

### ISSUE THREAD

**Issue by neezer** [STRML/react-router-component#114]
Admit I'm still figuring out patterns around React for stuff like this, but I'm wondering about the case in which I have something like the following:

```jsx
<Locations path={this.props.path}>                              
  <Location path="/" handler={HomePage} />                      
  <Location path="/landing-pages/:name" handler={LandingPage} />
  <NotFound handler={NotFoundPage} />                           
</Locations>                                                    
```

My issue is when I go to `/landing-pages/:name` (which is a valid route), but when given a `:name` that doesn't correspond to a record (doing a DB lookup to display data, a la `react-async`), I want to do the `NotFound` handler.

Is that possible? If so, I'd love an example! Thanks!

**Comment by STRML** [comment]
Hey @neezer,

I would suggest in this case to wrap `<LandingPage>` in a component that does the async fetch. If it comes back with a record, render `<LandingPage>`, if not, render `<NotFoundPage>`.

If you have a way of knowing ahead of time what the valid values are, I have done something like this before:

```javascript
var dynamicRoot = new RegExp(app.root + 
  "base/(" + aCollection.pluck('aProperty').join('|') + ")$");
// ...
<Location path={dynamicRoot} handler={aHandler} />
```

**Comment by neezer** [comment]
Cool, think I got it working. Thanks for the tip!
