### ISSUE TITLE
Addressable lightbox

### ISSUE THREAD

**Issue by relationshipshapes** [STRML/react-router-component#118]
Hi everyone, i'm trying to get an addressable lightbox working much like Facebook when you click on a photo. The page you are viewing does not change but a lightbox opens and the location changes.

For example: when viewing /gallery and I click on a image a lightbox should open and the location should change to /photo/1, but the gallery page should still be in the background.

So far I have tried a multiple router approach as described in mutiple.md with a main router and a lightbox router combined in my app, but then both routers have to handle /photo/1 and /gallery is navigated away from in the main router. If I could some how let my main router ignore this location change and only have the lightbox router respond then that seems like it would work. However,  this does not seem like the right approach.

Anyone have experience with this use case?

**Comment by jamwaffles** [comment]
I also have this use case (and issue). I thought it would "just work" with two routers side by side but it didn't for various reasons I didn't note down. I ended up just having a normal modal component I copy require and insert wherever it's required which isn't particularly elegant.

**Comment by STRML** [comment]
I think this could be done with two routers as you have proposed, if you change the routes. How about `/gallery*` as the route for the gallery page in the first router, then host the photo routes at `/gallery/photo/1`?

**Comment by jamwaffles** [comment]
I'm not sure it would work in my case; I need to have a modal that can pop up from anywhere in the app, so I could be on `/foo/bar` or /baz/quux` but the modal route `/global/modal` (relative to root) should _always_ fire, but I'm not sure RRC can support this. If I have 2 routers _next_ to each other would this work?

**Comment by relationshipshapes** [comment]
Thanks STRML I had considered something like that and the * operator definitely makes that easier. I think this solution could work for my needs since the modal content is usually directly relevant to the page content, but this does limit the functionality. For instance on facebook you can bring up a users photo modal from the news feed or the timeline while still maintaining the current background.

**Comment by STRML** [comment]
Yes. That's a hard use case to solve because it starts to become invisible state dependent, which is one of the things React tries to eliminate by design. For instance, if you click a photo on the news feed, and your URL changes to `yourdomain.com/photo/1`, when you refresh, what should you see? The gallery, or the news feed again? And if you're supposed to see the gallery, where is that "hidden state" that decides that the news feed should be in the background in the first instance?

In more traditional JS applications, the "hidden state" is in the DOM itself. But in React, it's going to need to be stored somewhere. Perhaps the answer is to write more complete URLs: one could argue there should be a /newsfeed/photo/<id>, and a /gallery/photo/<id>, because they really are two separate pages.

**Comment by relationshipshapes** [comment]
I see what you mean. However, on Faceboook if you refresh the photo you get a stand alone photo page, the state is lost.

**Comment by STRML** [comment]
Yeah. It makes sense for their particular use case, but in a way it
breaks the whole idea of a single url pointing to a single location.

**Comment by relationshipshapes** [comment]
Yeah true, there is 2 different modes. Show the stand alone page when no location has been loaded previous, and show the modal if a location has previous been loaded.

**Comment by pjuke** [comment]
I'm also interested in this feature; @relationshipshapes did you ever solved this issue?
I also want the solution as you described abode (two different modes).

**Comment by oyeanuj** [comment]
+1 @relationshipshapes @pjuke Did you ever solve this?

**Comment by pjuke** [comment]
@oyeanuj As a matter of fact I did.
Take a look at the https://github.com/reactjs/react-router/tree/master/examples/pinterest example, which I basically copied.

The idea is to set the lightbo data in location state. When that is being picked up in Application top-level component, save the current this.props.children and render them instead. When you reload the page; location state wont be present and the router will take care of the component being rendered.
