### ISSUE TITLE
It doesn't have an option to scroll up with route change

### ISSUE THREAD

**Issue by andre0799** [STRML/react-router-component#120]
Hey, I've looked through all the docs on how to change scroll behavior with react-router-component and I haven't found anything related to it. The default behavior is  that it keeps the scroll position, but I would like it to scroll to the top with every route change.

Thanks

**Comment by jsg2021** [comment]
For my app, it just does that on the `onNavigation` callback.

**Comment by andre0799** [comment]
but how do you set it on the onNavigation callback?

**Comment by jsg2021** [comment]
Something like this:

```jsx
export default React.createClass({
	displayName: 'Router',

	onNavigation () {
		if (global.scrollTo) {
			global.scrollTo(0,0);
		}
	},

	render () {
		return (
			<Locations onNavigation={this.onNavigation}> ...
		);
	},
...
```

**Comment by andre0799** [comment]
Oh, thanks! But yeah, that's how I was doing. The problem with that is that for a millisecond it scrolls to the top before actually rendering the new route. So I get a weird blink.

Any ideas on how to avoid that?

**Comment by andre0799** [comment]
I just moved this:

if (global.scrollTo) {
            global.scrollTo(0,0);
        }

to inside the render function. Instead of doing on the onNavigation callback.

**Comment by jsg2021** [comment]
You probably don't want it in the render method. That gets called quite often.  What if you use setTimeout in your onNavigation callback. Use 1ms or some very small timeout then scrollTo?
