### ISSUE TITLE
Bug with scroll when route changes 

### ISSUE THREAD

**Issue by andre0799** [STRML/react-router-component#125]
I described this bug here:

https://github.com/chadpaulson/react-isomorphic-video-game-search/issues/3

If you guys can please help. It would be appreciated. Thanks

**Comment by jsg2021** [comment]
I don't think the router is doing anything with scroll. However, when the dom changes scroll position may be affected. For example:
Rendering one route that is taller, then, rendering a new route that is shorter... then back to a tall route.

**Comment by andre0799** [comment]
Yeah, that's exactly the problem I'm having. All I wanted was the app
behaving like a regular website I guess. Where when you go to a new route
the scroll is up at the top, but when you go back it's where it was before
you changed to the new route . Do you have any ideas of what is the best
path I could take to solve this? Any ideas? Or maybe a work around to that.

Thank you,

Andre

**Comment by jsg2021** [comment]
In my app, I'm just scrolling to the top `onNavigation`

You could have a `onBeforeNavigation` callback save the scroll position in a map keyed by env.getPath(), then have a `onNavigation` callback that restores the position...while defaulting to 0?
