### ISSUE TITLE
Bump react-async dependency

### ISSUE THREAD

**Issue by shadeglare** [STRML/react-router-component#130]
Bump react-async dependency to 2.1.x

**Comment by STRML** [comment]
The current version range covers 2.1.

**Comment by jquense** [comment]
The current range does not cover this, you want `^2.0.0`. The tilde is only patch versions. It is currently  impossible to install with react `0.13`, because react-async `2.0.x` has a peer dep on `~0.12.0`.

**Comment by STRML** [comment]
Ah sorry, didn't realize it was an `~` range and not a `^` range. Will fix.

**Comment by STRML** [comment]
See `0.24.4`

**Comment by jquense** [comment]
many thanks!! :)
