### ISSUE TITLE
How to specify the LocalStorageKeyEnvironment?

### ISSUE THREAD

**Issue by kenjiru** [STRML/react-router-component#131]
I want to use the LocalStorageKeyEnvironment. I assume this can be specified like this:
```xml
<Locations environment={LocalStorageKeyEnvironment}>
    <Location path="home" handler={MainPage} />
...
```
But how do I access the LocalStorageKeyEnvironment? I was expecting it to be exported by `lib/environment/index.js`, but I can't see it exposed anywhere.

Am I missing something here?

**Comment by jsg2021** [comment]
You need to import it directly
```
import {getEnvironment} from 'react-router-component/lib/environment/LocalStorageKeyEnvironment';
```

or
```
var getEnvironment = require('react-router-component/lib/environment/LocalStorageKeyEnvironment').getEnvironment;
```

then, call `getEnvironment('key')` the returned instance is what you pass to the Locations environment prop.

**Comment by kenjiru** [comment]
It looks a bit more cumbersome then I expected, but it's ok. Thanks.
