### ISSUE TITLE
Hash change triggered by page links do not trigger Router

### ISSUE THREAD

**Issue by crockpotveggies** [STRML/react-router-component#132]
Using React 0.12 with v0.23.1.

Set up an app using the following structure, indents describe sub-components:

```
app.jsx
- page.jsx
-- board.jsx
-- home.jsx
-- notFound.jsx
```

My `page.jsx` looks like the following:
```
module.exports = function(React, Locations, Location, Home, Board, NotFound) {
  return React.createClass({

    render: function() {
        return (
          <Locations hash>
            <Location path="/sb/home" handler={Home({title: 'Home'})} />
            <Location path="/sb/trending-products" handler={Board({title: 'Trending Products'})} />
            <Location path="/*" handler={NotFound} />
          </Locations>
        );
    }

  });
};
```

The problem is that when I use both a traditional <a> tag and the <Link> component, neither one triggers a hash change. My links look like the following: `<Link href="#/sb/home">Home</Link>`. However, if I hit "enter" on the address bar in the browser, it will trigger a routing event and change the page.

Is this a config issue or a bug?

**Comment by crockpotveggies** [comment]
Just an update I've also tried moving <Locations> to the top-level app.jsx component and it still fails. What's weirder is that it's failing and only matching on the first <Location> in the routes.

**Comment by jsg2021** [comment]
I think you need the `<CaptureClicks>` around your `<Locations>`

is in: `react-router-component/lib/CaptureClicks`

**Comment by crockpotveggies** [comment]
Apologies for not updating this. I actually reached out to the React.js community to seek help on the issue and forgot about responding to this ticket!

The root cause of the problem was that I was not properly implementing `componentWillReceiveProps`. So even though there were different routes with different IDs and props, the component was still mounted. So when new props were passed to it, the component wouldn't update accordingly.

I will mark this as resolved and safely assume the root cause was my lack of understanding of props ;)

**Comment by darkyen** [comment]
I have the same issue, but i don't have any componentWillRecieveProps or anything :-/
