### ISSUE TITLE
React 0.13.x

### ISSUE THREAD

**Issue by khoerling** [STRML/react-router-component#137]
Is support on the horizon?

**Comment by STRML** [comment]
Yep, working on it as I convert my personal projects to 0.13.

Are there any compatibility issues you've seen?

**Comment by cainvommars** [comment]
Actually we're using it since a couple of weeks already with 0.13.2. No known issues so far.

```
"react": "^0.13.2",
"react-router-component": "^0.24.4",
```

**Comment by STRML** [comment]
Ah yes. I'm starting to lose my memory. We went through this before; 0.13 is fine with RRC. See #128.

This is why the latest ver relaxes the peerdep.

**Comment by jsg2021** [comment]
I'm on React 0.13.3, all fine except one proptype warning.
