### ISSUE TITLE
The updated url-pattern matches :named parts differently

### ISSUE THREAD

**Issue by jsg2021** [STRML/react-router-component#140]
It should be noted in versions prior to 0.25 url patterns that had `/object/:id` pattern would match things that would not (by default) match in in 0.25+

Example:
```
/object/some.object.12
```
doesn't match anymore for pattern `/object/:id`

I don't think we should fix that, but we should make it known.  ...as well as make it easy to override the `UrlPattern.Compiler`.

**Comment by STRML** [comment]
Thanks. This must be a side-effect of the new version of `url-pattern`.

I agree about exposing UrlPattern.Compiler.

**Comment by jsg2021** [comment]
What would be the preferred approach? I can't upgrade my app to use 0.25 until i can alter the compiler. (my route variable values contain periods and such and do not match with the defaults)

I'm just spitballing here, but we could have a static method on the router components like `Pages` and `Locations` that sets the default compiler for all instances of those components.

And/Or we can pass the compiler as a prop to those Pages/Locations components. If we do that, we should also pass that prop value down through context... obviously, sub-routers can override... maybe we add flag prop to indicate the compiler should be on context or not.

```
<Locations urlPatternCompiler={} makeUrlPatternCompilerDefaultForChildren>
    <Location .../>
    ...
</Locations>
```

I don't mind implementing it.

**Comment by STRML** [comment]
I think it is a bit much to expose this as a prop - rather, I would expose it as a static property on RRC itself and allow it to be overridden by being reassigned. Then, I would just expect a user who needs to override it to do so after requiring the module.

**Comment by STRML** [comment]
This is in `0.25.2`, see [the docs](http://strml.viewdocs.io/react-router-component/override-url-pattern) and [the tests](https://github.com/STRML/react-router-component/blob/master/tests/matchRoutes.js#L71).

**Comment by jsg2021** [comment]
@STRML Thats awesome.  Thanks.

One quick glitch though... in ES6, (babel transpiled code) you cannot modify a module's exports.

```
import * as Router from 'react-router-component';
Router.createURLPatternCompiler = () => {};
```
doesn't work as expected. `Router` is a local objects with references to the exports of rrc. Any modifications to `Router` are local to my current module.

what if you add a setter? eg: `setCreateURLPatternCompilerFactory (func)`

**Comment by STRML** [comment]
Ah, that is interesting to know.

I'll modify the API and re-release.

**Comment by jsg2021** [comment]
:+1:

**Comment by STRML** [comment]
Good to go in `0.25.3`. From the docs:

```javascript
import * as Router from 'react-router-component';
import * as URLPattern from 'url-pattern';

Router.setCreateURLPatternCompilerFactory((routeProps) => {
  var compiler = new URLPattern.Compiler();
  compiler.segmentValueCharset = 'a-zA-Z';
  return compiler;
})
```

**Comment by jsg2021** [comment]
@STRML Sorry to ping again. This time i come with code: #146
