### ISSUE TITLE
Calling .navigate causes contextual router to fail

### ISSUE THREAD

**Issue by mikemorton** [STRML/react-router-component#141]
I've set up a contextual router similar to the one here: http://strml.viewdocs.io/react-router-component/contextual

However in my application I use a `<select>` element that allows a user to navigate to to a different route using a call to `.navigate()` in the onChange event.  I'm finding that I get a script error when I call navigate: `RouteRenderingMixin.js:15 Uncaught TypeError: Cannot read property 'ref' of null`

I've crafted the smallest test case I could come up with.  Simply click the button in the component and note the script error.

    var React = require('react');
    var Router = require('react-router-component');
    var Locations = Router.Locations;
    var Location = Router.Location;
    var NotFound = Router.NotFound;
    var Link = Router.Link;

    var Start = React.createClass({
      render: function () {
        return <div>content</div>
      }
    });

    var ASection = React.createClass({
      render: function () {
        return (<Locations contextual>
                  <Location path="/" handler={Start} />
                  <Location path="/:myval/" handler={Start} />
                </Locations>);
      }
    });

    var MyApp = React.createClass({
      render: function () {
        return (<div>
          <button onClick={this._onClick}>button that causes navigation</button>

          <Locations ref="testref">
            <Location path="/" handler={Start} />
            <Location path="/a(/*)" handler={ASection} />
          </Locations>
        </div>);
      },
      _onClick: function () {
        this.refs.testref.navigate('/a/fdsa');
      }
    });

    React.render(<MyApp/>, document.body);

**Comment by epferrari** [comment]
Your error is from the trailing "/" on your `/:myval/ ` in ASection. Try this

```
var React = require('react');
var Router = require('react-router-component');
var Locations = Router.Locations;
var Location = Router.Location;
var NotFound = Router.NotFound;
var Link = Router.Link;

/* set this to watch yourself route to consecutive pages */
var i = 0;
var Start = React.createClass({
	render: function () {
		return <div>content {i}</div>
	}
});


var ASection = React.createClass({
	render: function () {
		return (<Locations contextual>
							<Location path="/" handler={Start} />
							<Location path="/:myval" handler={Start} />
						</Locations>);
	}
});

var MyApp = React.createClass({
	render: function () {
		return (<div>
			<button onClick={this._onClick}>button that causes navigation</button>

			<Locations ref="testref">
				<Location path="/" handler={Start} />
				<Location path="/a(/*)" handler={ASection} />
			</Locations>
		</div>);
	},
	_onClick: function () {
		i++;
		this.refs.testref.navigate('/a/ + i );
	}
});

React.render(<MyApp/>, document.body);
```

**Comment by STRML** [comment]
Please re-open if this is still a problem.
