### ISSUE TITLE
Owner-based and parent-based contexts differ warning

### ISSUE THREAD

**Issue by yizidz** [STRML/react-router-component#142]
Using Ubuntu 14.04LTS, Chrome, React 0.13.1.

Getting this error:

```
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (router) while mounting Link (see: http://fb.me/react-context-by-parent)
```

when using the ```Link``` component. Found that the error corresponds with line [16 of NavigatableMixin](https://github.com/STRML/react-router-component/blob/master/lib/NavigatableMixin.js#L16)

**Comment by jsg2021** [comment]
React 0.13.1 had a bug that caused it to erroneously warn about owner-parent contextual differences when any parent component in the hierarchy mounted with null or altered the root element in subsequent renders.  Try 0.13.3, all warnings should subside.

**Comment by vincent-li** [comment]
when I use 0.13.3 and the console have a error, Uncaught TypeError: Can't add property context, object is not extensible. Is there a bug? have some code to change ?

**Comment by germatpreis** [comment]
i am experiencing the same problem as @vincent-li. using react@0.13.3 and react-router-component@0.26.0. Any hints on how to proceed?

```
Uncaught TypeError: Can't add property context, object is not extensible
```

**Comment by jsg2021** [comment]
Did you define a "context" property or method on your component?

**Comment by germatpreis** [comment]
No, the problem is much simpler. I read the documentation to quickly and missed

> If you are using JSX, don't forget to bring components from a library into scope, cause JSX doesn't support namespaces yet:
var Locations = Router.Locations
var Location = Router.Location

and only read

> Otherwise, as of React 0.12, you must create factories:
var Locations = React.createFactory(Router.Locations)
var Location = React.createFactory(Router.Location)

Embarassing, but i blame the lack of coffee.

**Comment by jsg2021** [comment]
:+1: no worries

**Comment by STRML** [comment]
Please reopen if you are still having issues - looks like you worked it out.
