### ISSUE TITLE
Accessing isPopState

### ISSUE THREAD

**Issue by Wildhoney** [STRML/react-router-component#147]
@STRML I've switched from `react-router` because I noticed that the [`react-router-page-transition`](https://github.com/andreypopp/react-router-page-transition) module uses `react-router-component`, which takes advantage of the `isPopState` property.

However, I have an ES6 app &mdash; therefore no mixins &mdash; but I **need** access to the `isPopState` property to determine which animation to apply to my page transition &ndash; either left-to-right, or right-to-left.

How would I go about achieving this from inside of my React component?

**Comment by STRML** [comment]
Hi Adam,

Since mixins are now (unfortunately) dead, we have to go about it in
different ways. I recommend using react-mixin or a decorator. I plan to
test all of this out myself soon and write official docs for users avoiding
mixins.

**Comment by Wildhoney** [comment]
Thanks @STRML &ndash; I've tried to use `react-mixin` but receive the following when trying to mix in the `RouterMixin` object:

> Uncaught Error: Invariant Violation: Default.getChildContext(): childContextTypes must be defined in order to use getChildContext().

Without the `ReactMixin(Default.prototype, RouterMixin);` line, everything works perfectly. I'm not sure what I'm doing wrong.

```javascript
import React           from 'react';
import ReactMixin      from 'react-mixin';
import { RouterMixin } from 'react-router-component';

export default class Default extends React.Component {
    
    render() {
        // ...
    }

}

Default.contextTypes = {
    router: React.PropTypes.func
};

ReactMixin(Default.prototype, RouterMixin);
```

**Comment by STRML** [comment]
It appears support for `childContextTypes` was added [here](https://github.com/brigand/react-mixin/pull/5/files) but there must be something wrong with how we interact with it. I'll try to get a basic working version going.

**Comment by Wildhoney** [comment]
Thanks :+1: That'd be great.

**Comment by STRML** [comment]
Alright, try [the docs](http://strml.viewdocs.io/react-router-component/recipes/es6-custom-router) and [the example](https://github.com/STRML/react-router-component/blob/master/examples/es6/app.js).

**Comment by STRML** [comment]
The issue in your code was that you should be using `ReactMixin.onClass(Default, RouterMixin)` rather than `ReactMixin(Default.prototype, RouterMixin)`.

You could also use the decorators which are quite nice.

**Comment by Wildhoney** [comment]
Thanks @STRML Very helpful! It all compiles now, but I receive an error:

> RouterMixin.js:78 Uncaught TypeError: this.getRoutes is not a function

I'm not using the decorator approach &ndash; although I will do. I'm trying to import the `RouterMixin` so that I have access to `this.state.navigation.isPopState`. Am I going down the right path?

**Comment by STRML** [comment]
Yeah, you're fine. You have to define `getRoutes` yourself. See [the example](https://github.com/STRML/react-router-component/blob/master/examples/es6/app.js#L22).

**Comment by STRML** [comment]
Please re-open if you have any more issues.

**Comment by Wildhoney** [comment]
Will do. Thanks for your help!
