### ISSUE TITLE
React 0.14 Incompatibility: Mutating props

### ISSUE THREAD

**Issue by parshap** [STRML/react-router-component#148]
Directly mutating props of a component is not possible in React 0.14. This was deprecated in React 0.13:

> Mutating props after an element is created is deprecated and will cause warnings in development mode; future versions of React will incorporate performance optimizations assuming that props aren't mutated
>
> https://facebook.github.io/react/blog/2015/02/24/react-v0.13-rc1.html#breaking-changes

I was testing the React 0.14 beta and found `react-router-component` currently [does this in `matchRoutes.js`](https://github.com/STRML/react-router-component/blob/5250359fddd87489a68e78b86f6fbfb86297c666/lib/matchRoutes.js#L36), which throws an error when running with `react@0.14.0-beta`:

```
TypeError: Can't add property pattern, object is not extensible
    at matchRoutes (node_modules/react-router-component/lib/matchRoutes.js:36:29)
    ...
```

`props.pattern` seems to be only be used in the same context, two lines down, so I think it would be an easy fix to just use a local variable `var pattern` instead of mutating `props.pattern`. This may be a breaking change though, as route components will no longer expose the pattern prop (though not sure if anyone actually depended on this behavior).

**Comment by STRML** [comment]
Thanks for letting me know. 

It's assigned to props.pattern as a form of caching. We could cache them elsewhere. I don't believe there is really any good use for children to be passed the pattern as a prop.

**Comment by STRML** [comment]
In fact, we actually remove that prop before passing props to the child. So it is likely safe to just cache this directly on the element itself.

**Comment by STRML** [comment]
Your issue should be fixed in `master`. Try it out.

**Comment by STRML** [comment]
Full React 0.14 support is coming soon.
