### ISSUE TITLE
Underlines in route break will the Router

### ISSUE THREAD

**Issue by nodegin** [STRML/react-router-component#151]
```
<Location path="/:test_prop" handler={MyComp} />

[Error: React-router-component: No route matched! Did you define a NotFound route?]
```

**Comment by nodegin** [comment]
In addition, is there any support for optional parameter? just like
```
<Location path="/:prop1/:prop2?" handler={MyComp} />
```
thanks!

**Comment by jsg2021** [comment]
The default optional parameter format is to wrap it in `()`
```
<Location path="/:prop1(/:prop2)" handler={MyComp} />
```

the default url pattern compiler will need to be tweaked for the underscore characters.

**Comment by jsg2021** [comment]
See these docs:
http://strml.viewdocs.io/react-router-component/override-url-pattern/

https://www.npmjs.com/package/url-pattern

**Comment by nodegin** [comment]
@jsg2021 thanks a lot

**Comment by STRML** [comment]
Thanks for handling this @jsg2021

**Comment by jsg2021** [comment]
no problem :)
