### ISSUE TITLE
Caching views?

### ISSUE THREAD

**Issue by jjvattamattom** [STRML/react-router-component#152]
I want behaviour similar to what the browser offers. If I scrolled down a long page, opened a new page and immediately went back, it would load the previous page at the same scroll position. react-router-component always re-renders the view and resets scroll, when we go back. How do I get the 'save scroll' with react-router-component?

**Comment by STRML** [comment]
Doing this specifically is outside the domain of RRC, but you can implement it yourself by using the `onBeforeNavigation` callback to save the scroll state, and the `onNavigation` callback to restore it. Keep a hash somewhere of routes and scroll states and you should have it done easily.
