### ISSUE TITLE
intercept routing under certain conditions

### ISSUE THREAD

**Issue by cainvommars** [STRML/react-router-component#155]
I want to intercept the users routing when he has unsaved changes and show a nice information on that. However, has anyone done this with rrc? Any ideas on how to approach this?

**Comment by jsg2021** [comment]
I've done this, but it has one major caveat... if the user tries to leave the app completely, you have to use it in combination with `onbeforeunload`

on the `defaultEnvironment` or which ever environment you use, capture `setPath`, and then replace it with something like: 

```
const SetPath = Symbol();
let {setPath} = ENVIRONMENT;

Object.assign(ENVIRONMENT, {
	[SetPath]: setPath,
	setPath: (...args) => {
		let [, options = {}] = args;
		let continueSetPath = () => ENVIRONMENT[SetPath](...args);

		if (options.isPopState || !maybeBlockNavigation(continueSetPath)) {
			continueSetPath();
		}
	}
});
```


```
maybeBlockNavigation (cb) {
	if (NavStore.getGuardMessage) {
		areYouSure(NavStore.getGuardMessage(), 'Attention!', {
			confirmButtonLabel: 'Leave',
			cancelButtonLabel: 'Stay'})
			.then(cb, ()=> {});
		return true;
	}
}
```

**Comment by cainvommars** [comment]
Found a workaround
