### ISSUE TITLE
Routing to same component doesn't receive new props

### ISSUE THREAD

**Issue by tamagokun** [STRML/react-router-component#156]
I have two different routes that are both handled by the same component. I've discovered that when navigating between the two routes, `componentWillReceiveProps` will not always get called, even though the component _should_ be getting new props from the named url parameters.

Example:

```js
<Locations>
  <Location path="/items/:category" handler={ItemListing} />
  <Location path="/items/:category/:filter" handler={ItemListing} />
</Locations>
```

I'm using `react-router-component 0.24.4` `react 0.13.2`

**Comment by STRML** [comment]
That's because you're actually rendering two separate items with two separate keys and React creates a whole new component when switching between them. `componentWillReceiveProps` is not called on the initial render.

You can fix this by making it a single route:

```
  <Location path="/items/:category(/:filter)" handler={ItemListing} />
```

**Comment by tamagokun** [comment]
Ah! That makes perfect sense. Thank you!
