### ISSUE TITLE
how to navigate outside react component?

### ISSUE THREAD

**Issue by gocreating** [STRML/react-router-component#157]
I am using alt.js as my flux implementation
I want to make route transitions in somewhere like `UserActions.login` or `UserActions.logout`

There is a `navigate` method can be called inside a react component,
but how do I use it outside the component like in an action?

**Comment by STRML** [comment]
After render, keep a ref to the router. I fire an action on init that contains the router ref.

Then, allow firing an action like `'NAVIGATE'`, which uses the router ref to call `router.navigate(path)`.

**Comment by gocreating** [comment]
@STRML Thanks for answer! I will try it!
