### ISSUE TITLE
Passing style to a "Location"

### ISSUE THREAD

**Issue by yrokhlin** [STRML/react-router-component#159]
Is there any way to pass style to the div component that holds the route? It's frustrating because it's the top most component for most views, and you can't apply style or className's to that top most div.

**Comment by STRML** [comment]
@yrokhlin There is no intermediate div component that holds the route. The component is [rendered directly](https://github.com/STRML/react-router-component/blob/master/lib/RouteRenderingMixin.js#L24).

**Comment by yrokhlin** [comment]
![image](http://i.imgur.com/Ka34H7M.png)

It appears to me that there is in fact a div there....
