### ISSUE TITLE
`CaptureClicks` not working

### ISSUE THREAD

**Issue by gocreating** [STRML/react-router-component#164]
I am using version 0.27.2, and here is my code:

```js
// routes.js
import React from 'react';
import { Location, Locations } from 'react-router-component';
import CaptureClicks from 'react-router-component/lib/CaptureClicks';

import HomePage from './flux/views/pages/HomePage';
import AboutPage from './flux/views/pages/AboutPage';

export default class App extends React.Component {
  render() {
    return <CaptureClicks>
      <Locations path={this.props.path}>
        <Location
          path="/"
          handler={HomePage} />
        <Location
          path="/about"
          handler={AboutPage} />
      </Locations>
    </CaptureClicks>;
  }
};
```

```js
// boot.js
import React from 'react';
import { render } from 'react-dom';
import Routes from '../routes';

render(<Routes />, document.getElementById('exseed_root'));
```

now it works fine when I requests `/` and `/about`

but there is an error when I clicks the anchor `<a href="/user/login">Login</a>`

![2015-12-07 5 47 04](https://cloud.githubusercontent.com/assets/5002343/11623855/9ea4edc2-9d0a-11e5-867c-b982606df8e6.png)

it doesn't send a request to server

what's the problem?

**Comment by STRML** [comment]
Sounds like `CaptureClicks` is working just fine.

You don't have a login route. What do you expect it to do?

If `/user/login` is not part of the app but is instead a static page, use `<a href="/user/login" rel="external">Login</a>`.

**Comment by gocreating** [comment]
Thanks for answering, it works!

But my problem is that I am not sure whether my `<a>` is internal or external

I have multiple entries and one shared navigator under my app, so the anchors might either be internal or external

I remember the old version `CaptureClicks` automatically detects whether a link is internal or external without specifying `rel="external"`

Is that deprecated?

**Comment by STRML** [comment]
Please refer to the code.

https://github.com/STRML/react-router-component/blob/207c3e8128c5206447fada66880507088821c6a1/lib/CaptureClicks.js#L78

If it is on the same domain, it cannot tell if it is external or not by just checking if you have a route for it. It will automatically mark links from other domains as external.
