### ISSUE TITLE
CaptureLinks bails sometimes.

### ISSUE THREAD

**Issue by jsg2021** [STRML/react-router-component#174]
See this [line](https://github.com/STRML/react-router-component/blob/master/lib/CaptureClicks.js#L110)

I'm noticing inadvertent page reloads. (its not easy to spot since the route works...the page just loads to where you were going...other than it's a longer page load since the document unloads an reloads)

I've been able to work around it by setting bail to true after if/elseif locally. What is that missing? Is that acceptable? or is there something wrong with the match in one of my contexts?  When the goToUrl loads my refreshed page, the routes work :/ so... thoughts?

**Comment by jsg2021** [comment]
I think it maybe bailing when reaching NotFound routes... which it shouldn't. right? I mean, that's a valid route.

**Comment by STRML** [comment]
This is intentional. The router doesn't have any way to know that a route that was generated by the app isn't valid but handled by some other part of the stack.

If you want to override this behavior, pass a goToUrl function:

```js
<CaptureClicks gotoURL={gotoURL}>

...
function gotoURL(url: string): void {
  if (isTargetInApp(url)) return;
  window.location.href = url;
}
```

**Comment by jsg2021** [comment]
far enough :)
