### ISSUE TITLE
Retaining route handler state during routing.

### ISSUE THREAD

**Issue by kansi** [STRML/react-router-component#175]
I have the following router
```jsx
<Locations  hash >
<Location path="/" handler={SideBarMainList1} />
<Location path="/group_list" handler={SideBarGroupList} />
</Location>
```
I visit `/group_list` and change the state of a dropdown list in this route and then go back to `/`. Now when i come back again to `/group_list` i cannot see the pervious state being retained.

It seems that with each route change the corresponding component is re-rendered. How can i just un-mount the component and then remount it keeping its state intact ?

**Comment by jsg2021** [comment]
Make your state external to the component... like in Flux's Stores.  The component's state will be lost on unmount. That's React, not the router.

**Comment by STRML** [comment]
Agreed, this is not an RRC issue, this is the way React works and you will run into it with any component that conditionally renders another component.
