### ISSUE TITLE
catch query parameters globally?

### ISSUE THREAD

**Issue by cainvommars** [STRML/react-router-component#179]
I'd like to get access to query parameters on every possible route. (Mostly some tracking parameters from other pages, social links) With _query I get it on a specific route. Is there a way to access them globally with rrc, or do I need an own solution?

**Comment by cainvommars** [comment]
Found another way.

**Comment by probablyVincentIp** [comment]
![wisdom_of_the_ancients](https://user-images.githubusercontent.com/12500559/187886635-d92770c3-b126-4257-be63-d05d0026dd5f.png)
