### ISSUE TITLE
Higher-Order Component

### ISSUE THREAD

**Issue by invisipunk** [STRML/react-router-component#183]
When attempting to create a Higher-Order Component to dynamically generate routes from an array, 

return (
    <Locations hash component={this.props.component}>
      {this.props.routes.map(function(route, j) {
        return <Location path={route.path} handler={route.handler} />;
      })}
      <NotFound handler={MainPage} />
    </Locations>);

this is the error I get 
"matchRoutes.js:40 Uncaught TypeError: Cannot read property 'handler' of undefined(…)". Is there workaround to accomplish this without using mixins?

**Comment by jsg2021** [comment]
Locations expects children to be an array of Location elements, the way you are structuring it, (which is valid to react, but not valid to this router) you are passing a single child Array[] with Location elements... there is one extra wrapper "node" around your Location elements.

To accomplish what you want, you have to call React.createElement directly.
```es6
const props = {hash: true, component: this.props.component};

React.createElement(Locations, props,
    ...this.props.routes.map(routes =>
         <Location path={route.path} handler={route.handler}/> ),
    <NotFound handler={MainPage}/>
);
```

or without es6:

```
var props = {hash: true, component: this.props.component};

var args = [Locations, props]
    .concat(this.props.routes.map(function(routes) { 
        return <Location path={route.path} handler={route.handler}/> ;
    })
    .concat(
        <NotFound handler={MainPage}/>
    );

React.createElement.apply(React, args);

**Comment by invisipunk** [comment]
Thanks so much!

**Comment by STRML** [comment]
Thanks @jsg2021!
