### ISSUE TITLE
Programmatically navigate?

### ISSUE THREAD

**Issue by williamle8300** [STRML/react-router-component#185]
Hi great project.

Is there a way to navigate programmatically to an url? Similar to using `<Link/>` but doing in a function/callback?

**Comment by williamle8300** [comment]
Nevermind. I figured it out. Just needed to use `history.pushState(null, null, '/endpoint')`. Thanks for making this minimally sexy library!

**Comment by williamle8300** [comment]
Actually that didn't work. Any help appreciated!

**Comment by STRML** [comment]
Get a `ref` to the router and call `router.navigate(path, options)`.

**Comment by williamle8300** [comment]
Thanks. For progeny here's a link with an example: https://github.com/STRML/react-router-component/issues/24#issuecomment-38753069

**Comment by williamle8300** [comment]
I just realized your example doesn't use mixins.
