### ISSUE TITLE
Warning: getDefaultProps 

### ISSUE THREAD

**Issue by tiagojsalmeida** [STRML/react-router-component#201]
### Summary:

Error in console:

```js
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```

### Steps to reproduce:
- Render any location with `react-router-component@0.37.0` and `react@15.5`.

### Expected behavior:
Should be using `defaultProps`.

**Comment by STRML** [comment]
Render any modal? Not sure what you mean. It is likely this is not an issue in RRC - we use createClass.

**Comment by tiagojsalmeida** [comment]
Sorry, I mean render any `location`.

**Comment by STRML** [comment]
Again, not seeing this. Please submit code or a repository that can reproduce, e.g. on https://codesandbox.io/.

**Comment by tiagojsalmeida** [comment]
You are right. Interesting because on my project the error is related to react-router-component but on sandbox it works fine.
https://codesandbox.io/s/mGgoz5q0

**Comment by STRML** [comment]
Okay. Best of luck with diagnosis.
