### ISSUE TITLE
Location always renders a div

### ISSUE THREAD

**Issue by mikaelharsjo** [STRML/react-router-component#206]
For styling reasons we wan't to avoid extra divs in the markup.
`<Location />` always renders a `div`.
Would be nice to at least have the option to render `<React.Fragment>` instead.

**Comment by STRML** [comment]
Yes, Fragment is now an option. Accepting PRs.

**Comment by jsg2021** [comment]
`Locations` (router) component accepts a `component` prop which you can set to `null`.  The `Location` (routes) component renders the `handler` prop which you have total control of.

**Comment by STRML** [comment]
Ah yes. You're right that you can just pass the `component` and we have in fact done so in an app before without an issue. Coffee helps before commenting. Thanks for the note @jsg2021 and closing this as invalid.
