### ISSUE TITLE
Navigating from javascript

### ISSUE THREAD

**Issue by polmiro** [STRML/react-router-component#24]
First of all, thanks and congratulations on the library, it's the best I have seen when trying to run away from Backbone routers, and I have tried out quite a few things already.

How can I easily navigate to a route within the javascript context? For example, whenever an 401 is returned on my ajax call, I want to redirect the user to "/sessions/new". 

I am still getting to know the codebase and I can't seem to find a good entry point to do this. Am I missing something?

**Comment by saidimu** [comment]
For anyone else looking to redirect, here's a gist of a simple component that I use: https://gist.github.com/saidimu/2758402f7916f4e35dee

```
// jshint unused:true
var React = require('react');

var NavigatableMixin = require('react-router-component').NavigatableMixin;

var Redirect = React.createClass({
  mixins: [NavigatableMixin],

  _redirect: function(url) {
    this.navigate(url);
  },

  propTypes: {
    url: React.PropTypes.string.isRequired,
  },

  componentDidMount: function() {
    console.log('Redirecting to %s: ', this.props.url);
    this._redirect(this.props.url);
  },

  render: function() {
    return null;
  }
});//Redirect

module.exports = Redirect;
```
