### ISSUE TITLE
How to process routes with optional parameters ?

### ISSUE THREAD

**Issue by zerkalica** [STRML/react-router-component#7]
How to process routes like this:
`/step1/:search_path/:urn(/:agent)(?marker=:marker)`

Where agent and marker is optional.

**Comment by cainvommars** [comment]
@andreypopp I guess your advice from that ticket is still true? ( ? parameters are not in scope of rrc)

**Comment by STRML** [comment]
This has changed - optional parameters are supported in https://github.com/snd/url-pattern and querystring parsing is in http://strml.viewdocs.io/react-router-component/querystring/
